### PR TITLE
adding Readme instructions

### PR DESCRIPTION
**Pull request by piknik1979**

### CODE REVIEW

**Comment by Liam310** [comment]
Looks like all the right stuff is there, but when you're writing things like file names/file contents in an `md` file it can help to surround them with backticks like \`someCode\`. This will make it easier to read and differentiate, e.g.:

`.env.test`
with the text:  
`PGDATABASE=nc_test`

**Comment by Liam310** [comment]
As I write this, I just noticed - make sure the database names match up properly with the ones in the `sql` file!

**Comment by piknik1979** [comment]
@Liam310  I see now there was a mistake in a README.MD instructions I provided and I have changed this is there mistake anywhere else or I can Merge Pull request?
Do I have to do Another ticket in every case?

**Comment by Liam310** [comment]
@piknik1979 In general, if there is a significant change then you are welcome to submit another `nchelp` for a subsequent review. In this case it is a small superficial change so you can just go ahead and merge it once it's been fixed (and committed and pushed!)

**Pull request merged**
